//レコードプロジューサーで使用することを想定
/** This script is executed before the Record is generated
 * `current`- GlideRecord produced by Record Producer
 * Don't use `current.update()` or `current.insert()` as the record is generated by Record Producer
 * Don't use `current.setValue('sys_class_name', 'xxx')` as this will trigger reparent flow and can cause data loss
 * Avoid `current.setAbortAction()` and generate a separate record
 * Use `producer.var1` to access variables
 */

//current.email = producer.short_desc;
//インシデントの基本情報を件名とメールタブに記入
current.title = "【申告】" + producer.r_category;
current.email = "インシデント発生日時：" + producer.r_date + "\r\n" + producer.r_description + "\r\n";

//情報漏洩に関する情報を入力する。
current.sensitive_data_leak = producer.r_sensitive_data_leak;

//もし情報漏洩が有りなら、その内容をメールタブに追記する。
if (producer.r_sensitive_data_leak == "有り") {
    current.email += "漏洩情報： ";
}

//漏洩情報を追記していく。
if (producer.r_leaked_data_customer_info == "true") {
    current.email += "お客様の個人情報、";
}

if (producer.r_leaked_data_employee_info == "true") {
    current.email += "社員の個人情報、";
}

if (producer.r_leaked_data_unannounced_service_info == "true") {
    current.email += "未発表のサービスに関する情報";
}


//関係リストにレコードを新規作成するためにインシデントのレコードのsys_idを取得
var inc_id = current.sys_id;

//関連リストの影響ユーザーに値を入れていく。
var grAffectedUser = new GlideRecord('x_661859_ir_test_affected_user');
grAffectedUser.initialize();
grAffectedUser.parent_incident = inc_id;

grAffectedUser.name = producer.r_name;

if (producer.r_employee_num != "") {
    grAffectedUser.employee_number = producer.r_employee_num;
}

if (producer.r_dept_name != "") {
    grAffectedUser.dept = producer.r_dept_name;
}

grAffectedUser.insert();

//関連リストの影響ホストに値を入れていく。ホスト情報はない可能性があるので、その場合はスキップ
if (producer.r_pc_type != "" || producer.r_hostname != "" || producer.r_asset_num != "" || producer.r_system_name != "" || producer.r_system_num != "") {
    var grAffectedHost = new GlideRecord('x_661859_ir_test_affected_host');
    grAffectedHost.initialize();

    grAffectedHost.parent_incident = inc_id;

    if (producer.r_dept_name != "") {
        grAffectedHost.dept = producer.r_dept_name;
    }

    if (producer.r_pc_type != "") {
        grAffectedHost.host_type = producer.r_pc_type;
    }

    if (producer.r_hostname != "") {
        grAffectedHost.host_name = producer.r_hostname;
    }

    if (producer.r_asset_num != "") {
        grAffectedHost.asset_number = producer.r_asset_num;
    }

    //備考欄を初期化。追記でシステム名とシステム番号を入力するため。この手順はもしかすると不要かも。
    grAffectedHost.memo = "";

    //上書きしないように追記していく。
    if (producer.r_system_name != "") {
        grAffectedHost.memo += "システム名：";
        grAffectedHost.memo += producer.r_system_name;
    }

    if (producer.r_system_num != "") {
        grAffectedHost.memo += " システム番号：";
        grAffectedHost.memo += producer.r_system_num;
    }

    grAffectedHost.insert();

}